packages = ["fish", "hyprland", "eww", "swaync", "swayimg", "mimeapps"]

[variables]
laptop = false

[files]
"euphoria/monitor.conf" = "~/.config/hypr/conf/monitor.conf"
"euphoria/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
