packages = ["fish", "hyprland"]

[variables]
wallpaper = "~/Images/columns.jpg"
laptop = false

[files]
"euphoria/monitor.conf" = "~/.config/hypr/conf/monitor.conf"
"euphoria/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
