packages = ["fish", "hyprland", "swaync"]

[variables]
laptop = true

[files]
"flutterby/monitor.conf" = "~/.config/hypr/conf/monitor.conf"
"flutterby/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
"flutterby/hemnet.fish" = "~/.config/fish/conf.d/hemnet.fish"
