[fish]
depends = ["starship"]

[fish.files]
fish = "~/.config/fish"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[hyprland]
depends = ["tofi", "waybar"]

[hyprland.files]
hyprland = "~/.config/hypr"

[tofi.files]
tofi = "~/.config/tofi/config"

[waybar.files]
waybar = "~/.config/waybar"

[waybar.variables]
laptop = false

[eww.files]
eww = "~/.config/eww"

[swaync.files]
swaync = "~/.config/swaync"